### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by mccarlosen** [romelgomez/expo0auth#1]
I have tried logging in with facebook, but I get this error. 🤔

![image](https://user-images.githubusercontent.com/8524361/97713234-8e987880-1a8d-11eb-8092-12dfba4de186.png)

Any idea

**Comment by romelgomez** [comment]
Hi @mccarlosen, that is because I have the facebook app in developer mode, I recently change the mode to Live mode, 

![Screenshot from 2020-10-30 12-54-02](https://user-images.githubusercontent.com/2358251/97740282-088d2980-1aaf-11eb-8bef-25a5baebca09.png)

I should be fitx the issue.

Thanks

**Comment by mccarlosen** [comment]
Ok, thanks
